### ISSUE TITLE
api网关需要集成一下吧，需要统一管理起来

### ISSUE THREAD

**Issue by sunbiaozj** [galaxy-sea/heifer#2]
api网关需要集成一下吧，需要统一管理起来

**Comment by galaxy-sea** [comment]
已经配置完毕, 只要配置nacos配置 即可开箱即用,  个性化配置需要单独创建一个工程引用heifer-gateway后做定制

https://github.com/galaxy-sea/heifer/tree/main/heifer/heifer-gateway
