### ISSUE TITLE
会话 有状态和无状态的模式都完善一下 能都支持 通过配置模式有用户来决定使用哪种

### ISSUE THREAD

**Issue by sunbiaozj** [galaxy-sea/heifer#3]
会话 有状态和无状态的模式都完善一下 能都支持 通过配置模式有用户来决定使用哪种

**Comment by galaxy-sea** [comment]
支持无状态session，具体实现使用[Spring Cache Abstraction](https://docs.spring.io/spring-framework/docs/current/reference/html/integration.html#cache)
