### ISSUE TITLE
麻烦相关的基础框架包升级到最新版本一下 谢谢

### ISSUE THREAD

**Issue by sunbiaozj** [galaxy-sea/heifer#5]
麻烦相关的基础框架包升级到最新版本一下 谢谢

**Comment by galaxy-sea** [comment]
等待2月底Spring Cloud Alibaba新版本发布后统一升级依赖版本

**Comment by galaxy-sea** [comment]
Spring Cloud Alibaba升级到2021.0.1.0
Spring Cloud升级到 2021.0.1
Spring Boot升级到2.6.3

**Comment by galaxy-sea** [comment]
已升级Spring Cloud Alibaba
